from datetime import datetime
from flask_login import UserMixin
from app import db
import pytz

def get_current_time():
    """Return IST time (UTC+5:30)"""
    tz = pytz.timezone('Asia/Kolkata')
    return datetime.now(tz).replace(tzinfo=None)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)
    is_blocked = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=get_current_time)
    last_login = db.Column(db.DateTime)
    
    url_checks = db.relationship('URLCheck', backref='user', lazy=True, cascade='all, delete-orphan')
    password_checks = db.relationship('PasswordCheck', backref='user', lazy=True, cascade='all, delete-orphan')
    generated_passwords = db.relationship('GeneratedPassword', backref='user', lazy=True, cascade='all, delete-orphan')
    personal_passwords = db.relationship('PersonalPasswordGeneration', backref='user', lazy=True, cascade='all, delete-orphan')
    survey_responses = db.relationship('SurveyResponse', backref='user', lazy=True, cascade='all, delete-orphan')

class URLCheck(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    url = db.Column(db.Text, nullable=False)
    is_safe = db.Column(db.Boolean, nullable=False)
    security_score = db.Column(db.Integer, default=0)
    threat_types = db.Column(db.Text)
    phishing_status = db.Column(db.String(50), default='Clean')
    ssl_status = db.Column(db.String(50), default='Unknown')
    malware_status = db.Column(db.String(50), default='Clean')
    domain_age = db.Column(db.Integer)
    detailed_analysis = db.Column(db.Text)
    mistake_description = db.Column(db.Text)
    recommendations = db.Column(db.Text)
    checked_at = db.Column(db.DateTime, default=get_current_time)
    ip_address = db.Column(db.String(45))

class PasswordCheck(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    password_hash = db.Column(db.String(256))
    strength_score = db.Column(db.Integer, default=0)
    strength_level = db.Column(db.String(20), default='Very Weak')
    has_uppercase = db.Column(db.Boolean, default=False)
    has_lowercase = db.Column(db.Boolean, default=False)
    has_numbers = db.Column(db.Boolean, default=False)
    has_symbols = db.Column(db.Boolean, default=False)
    entropy = db.Column(db.Float, default=0.0)
    feedback = db.Column(db.Text)
    detailed_analysis = db.Column(db.Text)
    mistake_description = db.Column(db.Text)
    recommendations = db.Column(db.Text)
    checked_at = db.Column(db.DateTime, default=get_current_time)
    ip_address = db.Column(db.String(45))

class GeneratedPassword(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    password_hash = db.Column(db.String(256))
    length = db.Column(db.Integer, default=12)
    include_uppercase = db.Column(db.Boolean, default=True)
    include_lowercase = db.Column(db.Boolean, default=True)
    include_numbers = db.Column(db.Boolean, default=True)
    include_symbols = db.Column(db.Boolean, default=True)
    exclude_ambiguous = db.Column(db.Boolean, default=False)
    strength_score = db.Column(db.Integer, default=0)
    usage_purpose = db.Column(db.String(100))
    generated_at = db.Column(db.DateTime, default=get_current_time)
    ip_address = db.Column(db.String(45))

class PersonalPasswordGeneration(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    password_hash = db.Column(db.String(256))
    purpose = db.Column(db.String(200))
    length = db.Column(db.Integer, default=12)
    include_uppercase = db.Column(db.Boolean, default=True)
    include_lowercase = db.Column(db.Boolean, default=True)
    include_numbers = db.Column(db.Boolean, default=True)
    include_symbols = db.Column(db.Boolean, default=True)
    exclude_ambiguous = db.Column(db.Boolean, default=False)
    strength_score = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, default=get_current_time)
    last_updated = db.Column(db.DateTime, default=get_current_time, onupdate=get_current_time)
    is_active = db.Column(db.Boolean, default=True)

class SurveyResponse(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    experience_level = db.Column(db.String(50))
    primary_concern = db.Column(db.String(100))
    tools_used = db.Column(db.Text)
    satisfaction_rating = db.Column(db.Integer)
    improvement_suggestions = db.Column(db.Text)
    feature_requests = db.Column(db.Text)
    submitted_at = db.Column(db.DateTime, default=get_current_time)
    is_reviewed = db.Column(db.Boolean, default=False)
    reviewer_notes = db.Column(db.Text)
    ip_address = db.Column(db.String(45))

class SecurityReport(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    report_type = db.Column(db.String(50), nullable=False)
    related_check_id = db.Column(db.Integer)
    file_path = db.Column(db.String(500))
    file_format = db.Column(db.String(10))
    generated_at = db.Column(db.DateTime, default=get_current_time)
    download_count = db.Column(db.Integer, default=0)
    last_downloaded = db.Column(db.DateTime)
    is_active = db.Column(db.Boolean, default=True)
